### PR TITLE
Fix passphrase callback

### LINKED ISSUE #4: C# SetPassphraseFunction cause access violation error
I am using latest ggpme-sharp with C# and VS2013, 
my GPG version is 2.2.10.
I run the example PgpEncryptDecrypt, the pinentry dialog is prompted for passphrase and the decryption works. 
then I set "pinentry-mode loopback" in gpg.conf, the MyPassphraseCallback is called, I passed the passphrase to it, 

        public static PassphraseResult MyPassphraseCallback(
               Context ctx,
               PassphraseInfo info,
               ref char[] passwd)
        {
            passwd = Console.ReadLine().ToCharArray();

            return PassphraseResult.Success;
        }

now an unhandled is throws in gpgme-sharp\context.cs which says:

"An unhandled exception of type 'System.AccessViolationException' occurred in gpgme-sharp.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

the corresponding code is at line 621:

                    int err = libgpgme.gpgme_op_decrypt(
                        CtxPtr,
                        cipher.dataPtr,
                        plain.dataPtr);

I think this maybe an issue in codes because if I decrypt using command line (gpg -d filename) and input password in the command line, the decryption also success. 

Could you please help with it? thanks.

### PR DESCRIPTION
**Pull request by Daniel15**
Fixes the passphrase callback functionality.

 - Added `gpgme_set_pinentry_mode` call, as this is required to use the passphrase callback in GnuPG 2.1+
 - Write a newline rather than null byte after writing the passphrase
 - Mark the callback as `cdecl` so it doesn't corrupt the stack after being called. Fixes #4

### CODE REVIEW

File: gpgme-sharp/Context.cs [hunk 1]
```diff
@@ -142,6 +142,53 @@ private void Initialize(ref ContextSigners signers, ref ContextSignatureNotation
...
+            set
+            {
+                if (IsValid)
+                {
+                    lock (CtxLock)
+                    {
+                        var mode = (gpgme_pinentry_mode_t)value;
+                        int err = libgpgme.NativeMethods.gpgme_set_pinentry_mode(CtxPtr, mode);
+
+                        gpg_err_code_t errcode = libgpgme.gpgme_err_code(err);
```
Comment (Daniel15) [inline gpgme-sharp/Context.cs:169]: I'll submit a separate PR to clean up all this error handling code - A lot of it is copy-pasted right now, unfortunately.
